general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Iosevka Nerd Font Mono" }
bold = { family = "Iosevka Nerd Font Mono" }
italic = { family = "Iosevka Nerd Font Mono" }
size = 14

[window]
dynamic_padding = true
padding.x = 0
padding.y = 0
decorations = "None"
opacity = 0.88

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
