general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font" }
bold = { family = "CaskaydiaMono Nerd Font" }
italic = { family = "CaskaydiaMono Nerd Font" }
size = 12

[window]
dynamic_padding = true
padding.x = 4
padding.y = 4
decorations = "None"
opacity = 0.88

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
