theme = "gruber-darker"

[editor]
line-number = "relative"
mouse = false
scrolloff = 8
shell = ["zsh", "-c"]
cursorline = true
continue-comments = false
color-modes = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal.space]
space = "command_mode"

[keys.normal."+"]
m = ":sh make"
